name: coingecko
jobs:
  ping:
    steps:
      - uri: wrap://fs/./build
        method: ping
  supported_vs_currencies:
    steps:
      - uri: wrap://fs/./build
        method: simpleSupportedVsCurrencies
  coins_list:
    steps:
      - uri: wrap://fs/./build
        method: coinsList
  coins_markets:
    steps:
      - uri: wrap://fs/./build
        method: coinsMarkets
        args:
          vs_currency: "usd"
  coin:
    steps:
      - uri: wrap://fs/./build
        method: coin
        args:
          id: "bitcoin"
  coins_tickers:
    steps:
      - uri: wrap://fs/./build
        method: coinsTickers
        args:
          id: "bitcoin"
  coins_history:
    steps:
      - uri: wrap://fs/./build
        method: coinsHistory
        args:
          id: "bitcoin"
          date: "27-08-2018"
  coins_market_chart:
    steps:
      - uri: wrap://fs/./build
        method: coinsMarketChart
        args:
          id: "bitcoin"
          vs_currency: "usd"
          days: "1"
  coins_market_chart_range:
    steps:
      - uri: wrap://fs/./build
        method: coinsMarketChartRange
        args:
          id: "bitcoin"
          vs_currency: "usd"
          from: "1392577232"
          to: "1422577232"
  coins_contract:
    steps:
      - uri: wrap://fs/./build
        method: coinsContract
        args:
          id: "ethereum"
          contract_address: "0x0D8775F648430679A709E98d2b0Cb6250d2887EF"
  coins_contract_market_chart:
    steps:
      - uri: wrap://fs/./build
        method: coinsContractMarketChartRange
        args:
          id: "ethereum"
          contract_address: "0x0D8775F648430679A709E98d2b0Cb6250d2887EF"
          vs_currency: "usd"
          days: "1"
  coins_contract_market_chart_range:
    steps:
      - uri: wrap://fs/./build
        method: coinsContractMarketChartRange
        args:
          id: "ethereum"
          contract_address: "0x0D8775F648430679A709E98d2b0Cb6250d2887EF"
          vs_currency: "usd"
          from: "1392577232"
          to: "1422577232"
  coins_ohlc:
    steps:
      - uri: wrap://fs/./build
        method: coinsOhlc
        args:
          id: "ethereum"
          vs_currency: "usd"
          days: "1"
  asset_platforms:
    steps:
      - uri: wrap://fs/./build
        method: assetPlatforms
  coins_categories_list:
    steps:
      - uri: wrap://fs/./build
        method: coinsCategoriesList
  coins_categories:
    steps:
      - uri: wrap://fs/./build
        method: coinsCategories
  exchanges:
    steps:
      - uri: wrap://fs/./build
        method: exchanges
  exchanges_list:
    steps:
      - uri: wrap://fs/./build
        method: exchangesList
  exchange:
    steps:
      - uri: wrap://fs/./build
        method: exchange
        args:
          id: "bitforex"
  exchanges_tickers:
    steps:
      - uri: wrap://fs/./build
        method: exchangesTickers
        args:
          id: "bitforex"
  # exchange_rates:
  #   steps:
  #     - uri: wrap://fs/./build
  #       method: exchangeRates
  indexes:
    steps:
      - uri: wrap://fs/./build
        method: indexes
  market_indexes:
    steps:
      - uri: wrap://fs/./build
        method: marketIndexes
        args:
          market_id: "bitforex_futures"
          id: "ETH"
  indexes_list:
    steps:
      - uri: wrap://fs/./build
        method: indexesList
  derivatives:
    steps:
      - uri: wrap://fs/./build
        method: derivatives
  derivatives_exchanges:
    steps:
      - uri: wrap://fs/./build
        method: derivativesExchanges
  derivatives_exchange:
    steps:
      - uri: wrap://fs/./build
        method: derivativesExchange
        args:
          id: "binance_futures"
  derivatives_exchanges_list:
    steps:
      - uri: wrap://fs/./build
        method: derivativesExchangesList
  search_trending:
    steps:
      - uri: wrap://fs/./build
        method: searchTrending
  global:
    steps:
      - uri: wrap://fs/./build
        method: global
  global_decentralized_finance_defi:
    steps:
      - uri: wrap://fs/./build
        method: globalDecentralizedFinanceDefi
  companies_public_treasury:
    steps:
      - uri: wrap://fs/./build
        method: companiesPublicTreasury
        args:
          coin_id: "bitcoin"
